name: Create an issue
on:
  workflow_dispatch:
    
permissions:
  contents: read
  issues: write
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: update gh
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install gh	
      
      - name: Create an Issue
        env:
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          URL=$(gh issue create -t "create readme" -b "update readme or create readme" -a @me | grep "https://")
          echo $URL
          gh issue edit $URL --add-assignee @copilot
          
